export enum DocumentStatusEnum {
  AWAITING_VALIDATION = 'AWAITING_VALIDATION',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ON_HOLD = 'ON_HOLD',
  COMPLETE = 'COMPLETE',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NONE = 'NONE',
  VALID = 'VALID',
  VERIFIED = 'VERIFIED',
  FAIL = 'FAIL',
  PASS = 'PASS',
  NEW = 'NEW',
}
