export enum ResponseWrapperCodeEnum{
  OK = "OK",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND",
  UNAUTHORIZED_ACTION = "UNAUTHORIZED_ACTION",
  REGISTER_NOT_ELIGIBLE = "REGISTER_NOT_ELIGIBLE",
  OTP_SERVICE_UNAVAILABLE = "OTP_SERVICE_UNAVAILABLE",
  BAD_DATA_PROVIDED = "BAD_DATA_PROVIDED",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  DOCUMENT_STATE_INVALID = "DOCUMENT_STATE_INVALID",
  ALREADY_DONE = "ALREADY_DONE",
}
